name: PullRequestCheck

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    name: PullRequestCheck
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-cache-${{ matrix.os }}

      - name: Install Dependencies
        run: yarn

      - name: Build Project
        run: yarn build

      - name: Pack Electron app
        run: yarn run pack
